apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-node-firefox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: firefox
        image: selenium/node-firefox:3.14
