apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: selenium-grid
  name: selenium-grid
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-grid
    component: hub
  name: hub
  namespace: selenium-grid
spec:
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: selenium-grid
    component: hub
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: selenium-grid
    component: hub
  name: selenium-hub
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-grid
      component: hub
  template:
    metadata:
      labels:
        app: selenium-grid
        component: hub
    spec:
      containers:
      - image: selenium/hub:3.14
        name: hub
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: selenium-grid
    browser: chrome
    component: node
  name: selenium-node-chrome
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-grid
      browser: chrome
      component: node
  template:
    metadata:
      labels:
        app: selenium-grid
        browser: chrome
        component: node
    spec:
      containers:
      - image: selenium/node-chrome:3.14
        name: chrome
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: selenium-grid
    browser: firefox
    component: node
  name: selenium-node-firefox
  namespace: selenium-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-grid
      browser: firefox
      component: node
  template:
    metadata:
      labels:
        app: selenium-grid
        browser: firefox
        component: node
    spec:
      containers:
      - image: selenium/node-firefox:3.14
        name: firefox
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: selenium-grid
    component: hub
  name: selenium-hub
  namespace: selenium-grid
spec:
  rules:
  - host: selenium-hub.example.com
    http:
      paths:
      - backend:
          serviceName: selenium-hub
          servicePort: 4444
        path: /
